src/Entity/Routine.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TranslatableInterface;
use Knp\DoctrineBehaviors\Model\Translatable\TranslatableTrait;

/**
 * Routine.
 *
 * @ORM\Entity(repositoryClass="App\Repository\RoutineRepository")
 */
class Routine implements TranslatableInterface
{
    use TranslatableTrait;

    /**
     * @var int
     *
     * @ORM\Column(type="integer", nullable=false, options={"unsigned"=true})
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=80, nullable=true)
     */
    private $name_id;

    /**
     * @var Level
     *
     * @ORM\ManyToOne(targetEntity="Level")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(referencedColumnName="id")
     * })
     */
    private $level;

    /**
     * @var int
     *
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $sortOrder;

    /**
     * @var int
     *
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $featuredOrder;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(referencedColumnName="id")
     * })
     */
    private $user;

    /**
     * @var RoutineSequence[]|ArrayCollection
     *
     * @ORM\OneToMany(
     *      targetEntity="RoutineSequence",
     *      mappedBy="routine",
     *      orphanRemoval=true,
     *      cascade={"persist"}
     * )
     * @ORM\OrderBy({"sequenceOrder": "ASC"})
     */
    private $routineSequences;

    /**
     * @var string|null
     *
     * @ORM\Column(type="text", length=100, nullable=true)
     */
    private $author;

    /**
     * @var string|null
     *
     * @ORM\Column(type="text", length=100, nullable=true)
     */
    private $link;

    /**
     * @var int
     *
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $minDuration;

    /**
     * @var int
     *
     * @ORM\Column(type="smallint", nullable=true)
     */
    private $duration;

    /**
     * @var RoutineCategory
     *
     * @ORM\ManyToOne(targetEntity="RoutineCategory", inversedBy="routines")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(referencedColumnName="id")
     * })
     */
    private $routineCategory;

    /**
     * @var Collection
     *
     * @ORM\ManyToMany(targetEntity="Tag", inversedBy="routines")
     * @ORM\JoinTable(
     *   joinColumns={
     *     @ORM\JoinColumn(referencedColumnName="id")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(referencedColumnName="id")
     *   }
     * )
     */
    private $tags;

    public function __construct()
    {
        $this->routineSequences = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLevel(): ?Level
    {
        return $this->level;
    }

    public function setLevel(?Level $level): self
    {
        $this->level = $level;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getRoutineSequences(): Collection
    {
        return $this->routineSequences;
    }

    /**
     * @return string|null
     */
    public function getLink(): ?string
    {
        return $this->link;
    }

    /**
     * @param string|null $link
     */
    public function setLink(?string $link): void
    {
        $this->link = $link;
    }

    /**
     * @return string|null
     */
    public function getAuthor(): ?string
    {
        return $this->author;
    }

    /**
     * @param string|null $author
     */
    public function setAuthor(?string $author): void
    {
        $this->author = $author;
    }

    /**
     * @return Collection
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        if ($this->tags->contains($tag)) {
            $this->tags->removeElement($tag);
        }

        return $this;
    }

    /**
     * @return int
     */
    public function getDuration(): ?int
    {
        return $this->duration;
    }

    /**
     * @param int $duration
     */
    public function setDuration(int $duration): void
    {
        $this->duration = $duration;
    }

    /**
     * @return int
     */
    public function getFeaturedOrder(): ?int
    {
        return $this->featuredOrder;
    }

    /**
     * @param int $featuredOrder
     */
    public function setFeaturedOrder(int $featuredOrder): void
    {
        $this->featuredOrder = $featuredOrder;
    }

    /**
     * @return RoutineCategory
     */
    public function getRoutineCategory(): RoutineCategory
    {
        return $this->routineCategory;
    }

    /**
     * @param RoutineCategory $routineCategory
     */
    public function setRoutineCategory(RoutineCategory $routineCategory): void
    {
        $this->routineCategory = $routineCategory;
    }

    /**
     * @return string
     */
    public function getNameId(): string
    {
        return $this->name_id;
    }

    /**
     * @param string $name_id
     */
    public function setNameId(string $name_id): void
    {
        $this->name_id = $name_id;
    }

    /**
     * @return int
     */
    public function getMinDuration(): ?int
    {
        return $this->minDuration;
    }

    /**
     * @param int $minDuration
     */
    public function setMinDuration(?int $minDuration): void
    {
        $this->minDuration = $minDuration;
    }

    /**
     * @return int|null
     */
    public function getSortOrder(): ?int
    {
        return $this->sortOrder;
    }

    /**
     * @param int|null $sortOrder
     * @return Routine
     */
    public function setSortOrder(?int $sortOrder): Routine
    {
        $this->sortOrder = $sortOrder;

        return $this;
    }
}

src/Entity/RoutineTranslation.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TranslationInterface;
use Knp\DoctrineBehaviors\Model\Translatable\TranslationTrait;

/**
 * RoutineTranslation.
 *
 * @ORM\Entity
 */
class RoutineTranslation implements TranslationInterface
{
    use TranslationTrait;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     *
     * @var int
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=50, nullable=false)
     */
    private $name;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $subname = null;

    /**
     * @var string|null
     *
     * @ORM\Column(type="text", length=65535, nullable=true)
     */
    private $description = null;

    /**
     * @var string|null
     *
     * @ORM\Column(type="text", length=65535, nullable=true)
     */
    private $evolution = null;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=50, nullable=true)
     */
    private $license;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $license_url = null;

    public function getId(): int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getEvolution(): ?string
    {
        return $this->evolution;
    }

    public function setEvolution(?string $evolution): self
    {
        $this->evolution = $evolution;

        return $this;
    }

    public function getSubname(): ?string
    {
        return $this->subname;
    }

    public function setSubname(?string $subname): void
    {
        $this->subname = $subname;
    }

    public function getLicense(): ?string
    {
        return $this->license;
    }

    public function setLicense(?string $license): void
    {
        $this->license = $license;
    }

    public function getLicenseUrl(): ?string
    {
        return $this->license_url;
    }

    public function setLicenseUrl(?string $license_url): void
    {
        $this->license_url = $license_url;
    }
}

src/Controller/RoutineController.php
<?php

namespace App\Controller;

use App\Entity\Routine;
use App\Entity\RoutineCategory;
use App\Service\UserService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\Exception\ExceptionInterface;
use Symfony\Component\Serializer\SerializerInterface;

/**
 * Controller used to manage routine contents in the public part of the site.
 */
class RoutineController extends AbstractController
{
    /**
     * @Route("/routines", methods="GET", name="routine_index")
     *
     * @throws ExceptionInterface
     */
    public function index(Request $request, UserService $userService, SerializerInterface $serializer): Response
    {
        if (null === $userService->getCurrentUser($request)) {
            return $this->redirectToRoute('login');
        }

        $initialState = $userService->getInitialState($request);
        $initialState['routineCategories'] = $this->getDoctrine()->getRepository(RoutineCategory::class)->findRoutineCategoryWithRoutines($request->getLocale());

        return $this->render('index.html.twig', [
            'initialState' => $serializer->normalize($initialState),
        ]);
    }

    /**
     * @Route("/routines/{name_id}", methods="GET", name="routine_view")
     * @Route("/routines/{name_id}/run", methods="GET", name="routine_run")
     *
     * NOTE: The $post controller argument is automatically injected by Symfony
     * after performing a database query looking for a Post with the 'slug'
     * value given in the route.
     * See https://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html
     */
    public function routineViewAndRun(Request $request, Routine $routine, string $name_id, SerializerInterface $serializer, UserService $userService): Response
    {
        if (null === $userService->getCurrentUser($request)) {
            return $this->redirectToRoute('login');
        }

        $initialState = $userService->getInitialState($request);
        $initialState['routine'] = $this->getDoctrine()->getRepository(Routine::class)->findRoutine($name_id, $request->getLocale());
        $initialState['routine']['items'] = $this->getDoctrine()->getRepository(Routine::class)->getSessionItems($routine, $request->getLocale()); // Redundant, fetch two times Routine

        return $this->render('index.html.twig', [
            'initialState' => $serializer->normalize($initialState),
        ]);
    }
}

templates/routine/view.html.twig
{% extends 'base.html.twig' %}

{% block body_id 'routine_view' %}
{% block title %}{% if routine.translate(app.request.locale).name %}{{ routine.translate(app.request.locale).name }}{% else %}{{ routine.translate('en').name }}{% endif %}{% endblock %}

{% block main %}
    <h1>{% if routine.translate(app.request.locale).name %}{{ routine.translate(app.request.locale).name }}{% else %}{{ routine.translate('en').name }}{% endif %}</h1>
    {% if routine.translate(app.request.locale).subname %}
        <p class="lead">{{ routine.translate(app.request.locale).subname }}</p>
    {% elseif routine.translate('en').subname %}
        <p class="lead">{{ routine.translate('en').subname }}</p>
    {% endif %}
    <!--<p class="lead">routine.level.name</p>-->

    {% if routine.translate(app.request.locale).description %}
        <p class="mb-1">{{ routine.translate(app.request.locale).description|md2html }}</p>
    {% elseif routine.translate('en').description %}
        <p class="mb-1">{{ routine.translate('en').description|md2html }}</p>
    {% endif %}

    <p>
        {% if routine.author %}
            <strong>{{ 'label.author'|trans }}{% if app.request.locale == 'fr' %}&#8239;{% endif %}:</strong> {{ routine.author }}<br/>
        {% endif %}
        {% if routine.translate(app.request.locale).license %}
            <strong>{{ 'label.license'|trans }}{% if app.request.locale == 'fr' %}&#8239;{% endif %}:</strong> {% if routine.translate(app.request.locale).licenseUrl %}<a href="{{ routine.translate(app.request.locale).licenseUrl }}" rel="nofollow noreferrer">{% endif %}{{ routine.translate(app.request.locale).license }}{% if routine.translate(app.request.locale).licenseUrl %}</a>{% endif %}
            <br/>
        {% endif %}
        {% if routine.link %}
            <strong>{{ 'label.source'|trans }}{% if app.request.locale == 'fr' %}&#8239;{% endif %}:</strong> <a
                href="{{ routine.link }}" rel="nofollow noreferrer">{{ routine.link }}</a>
        {% endif %}
    </p>

    {% if sessionItems is not empty %}
        <h3>{{ 'label.plan'|trans }} (<span
                    title="Estimation based on 1 rep = 3 sec for reps-oriented exercises. System can't calculate MAX reps exercises">{{ duration }} min<sup>?</sup></span>)
        </h3>
        <a class="btn btn-outline-theme"
           href="{{ path('routine_run', {name_id: routine.nameId}) }}">{{ 'action.start_routine'|trans }}</a>
        <a class="btn btn-outline-secondary disabled" href="#">{{ 'action.export_csv'|trans }}</a>
        <span>&nbsp;</span>
        <strong><i class="fas fa-th-list"></i> {{ 'label.list'|trans }}</strong> / <a href="#"><i
                class="fas fa-th"></i> {{ 'label.grid'|trans }}</a> (coming soon)
        <table class="table table-responsive">
            <thead>
            <tr>
                <th scope="col">&nbsp;</th>
                <th scope="col">{{ 'label.name'|trans }}</th>
                <th scope="col">{{ 'label.current_set'|trans }}</th>
                <th scope="col">{{ 'label.reps_duration'|trans }}</th>
            </tr>
            </thead>
            <tbody>
            {% for sessionItem in sessionItems %}
                {% if sessionItem is iterable %}
                    <tr style="height: 100px">
                        <td class="align-middle" style="padding: 0">
                            {% if sessionItem[0].id is not null %}
                                <div class="img-square"
                                     style="position:relative; overflow:hidden; padding-bottom:100%; width: 100px">
                                    <img class="rounded mx-auto d-block"
                                         src="/img/exercise/{{ sessionItem[0].nameId }}.jpg" alt=""
                                         style="position: absolute; max-width: 100%; max-height: 100%; top: 50%; left: 50%; transform: translateX(-50%) translateY(-50%);"/>
                                </div>
                            {% endif %}
                        </td>
                        <td class="align-middle">
                            <select class="form-control progression progression{{ sessionItem[0].sequenceId }}">
                                {% for progressionSessionItem in sessionItem %}
                                    <option>{{ progressionSessionItem.name }}
                                        {% if progressionSessionItem.variant is not null and progressionSessionItem.variant != "" %} — {{ progressionSessionItem.variant }}{% endif %}</option>
                                {% endfor %}
                            </select>
                        </td>
                        <td class="align-middle">{% if sessionItem[0].maxSet is not null and sessionItem[0].maxSet > 1 %}Set {{ sessionItem[0].currentSet }}/{{ sessionItem[0].maxSet }}{% endif %}</td>
                        <td class="align-middle"><span
                                    class="badge badge-theme badge-pill">{{ sessionItem[0].quantityFormatted }}</span>
                        </td>
                    </tr>
                {% else %}
                    <tr style="height: 100px">
                        <td class="align-middle" style="padding: 0">
                            {% if sessionItem.id is not null %}
                                <div class="img-square"
                                     style="position:relative; overflow:hidden; padding-bottom:100%; width: 100px">
                                    <img class="rounded mx-auto d-block"
                                         src="/img/exercise/{{ sessionItem.nameId }}.jpg" alt=""
                                         style="position: absolute; max-width: 100%; max-height: 100%; top: 50%; left: 50%; transform: translateX(-50%) translateY(-50%);"/>
                                </div>
                            {% endif %}
                        </td>
                        <td class="align-middle">{% if sessionItem.id is not null %}<a
                                    href="{{ path('exercise_view', {name_id: sessionItem.nameId}) }}"
                                    class="card-link">{% endif %}
                                {{ sessionItem.name }}
                                {% if sessionItem.id is not null %}</a>{% endif %}
                            {% if sessionItem.variant is not null and sessionItem.variant != "" %}
                                <br/>{{ sessionItem.variant }}{% endif %}</td>
                        <td class="align-middle">{% if sessionItem.maxSet is not null and sessionItem.maxSet > 1 %}Set {{ sessionItem.currentSet }}/{{ sessionItem.maxSet }}{% endif %}</td>
                        <td class="align-middle"><span
                                    class="badge badge-theme badge-pill">{{ sessionItem.quantityFormatted }}</span></td>
                    </tr>
                {% endif %}
            {% else %}
                <div class="well">{{ 'routine.no_routines_found'|trans }}</div>
            {% endfor %}
            </tbody>
        </table>
        <a class="btn btn-outline-theme"
           href="{{ path('routine_run', {name_id: routine.nameId}) }}">{{ 'action.start_routine'|trans }}</a>
        <a class="btn btn-outline-secondary disabled" href="#">{{ 'action.export_csv'|trans }}</a>
    {% endif %}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('routine-view') }}
{% endblock %}